### ISSUE TITLE
Clean development files

### ISSUE THREAD

**Issue by mnblonsky** [NREL/OCHRE#45]
A few files seem unnecessary to be included in the public repo or need to be updated to work with the public repo:

- [x] Remove files used for validation
- [x] Remove old scripts and notebooks
- [x] Replace/remove private file paths
- [x] Replace Github Enterprise paths with public paths
- [x] Run all scripts and notebooks to make sure they run

**Comment by jmaguire1** [comment]
@mnblonsky : can we close this one?

**Comment by mnblonsky** [comment]
Yes.
