### ISSUE TITLE
Automatically add Envelope results to Dwelling results like in previous OCHRE versions? 

### ISSUE THREAD

**Issue by pemami4911** [NREL/OCHRE#64]
Hi! There used to be a line of code that would automatically add the Envelope results to the Dwelling results Dict, something like `out.update(self.envelope.generate_results())`. Is this going to get added back eventually in this function? https://github.com/NREL/OCHRE/blob/7b357be37dd2ca294775634d49b53df198b1a6a0/ochre/Dwelling.py#L281

Right now I can access the Envelope results directly by manually calling `self.dwelling.envelope.generate_results()`, so this isn't high priority.

**Comment by mnblonsky** [comment]
Hi @pemami4911, Sorry I hadn't seen this until today. I think the envelope results should still be in the Dwelling results dict. The envelope is now a "sub_simulator" of the dwelling, so its results get added to the dict here:
https://github.com/NREL/OCHRE/blob/ffea60445879985b5b7056576363aa800a3d0403/ochre/Simulator.py#L261

That should get called if you're calling `Dwelling.update()`. I did a quick check and I see all the envelope results there. Let me know if you're not seeing them though!

**Comment by pemami4911** [comment]
Thanks! Closing.
