### ISSUE TITLE
Floor area check doesn't equal floor area.

### ISSUE THREAD

**Issue by jmaguire1** [NREL/OCHRE#65]
In at least one case with a garage I'm hitting this warning for AC3:

WARNING: Indoor floor area calculations do not agree: 178.18803071999997 m^2 and 154.03324031999998 m^2

The first floor area (178 m^2) is the correct one.

**Comment by jmaguire1** [comment]
@mnblonsky: Here's why we're hitting this error https://github.com/NREL/OCHRE/blob/fffb9f431daa5ff05dbdd97bfc002754df0a0bb2/ochre/utils/hpxml.py#L406 

So the actual floor area IS correct, it's "indoor_floor_check" that's incorrect.

**Comment by mnblonsky** [comment]
The issue is with the `attic_floor_area`. Working on a fix now

**Comment by jmaguire1** [comment]
Closed via #67
