### ISSUE TITLE
Door Boundary R Value values in HPXML are not all equal

### ISSUE THREAD

**Issue by sugirdhalakshmi** [NREL/OCHRE#70]
I am having issues while running hpxml file for AC3 project. The xml file was created using BEopt. The error is Door Boundary R Value values in HPXML are not all equal: [5.0, 7.14]. I have attached the input xml, schedules and weather file for reference.
[Archive.zip](https://github.com/NREL/OCHRE/files/12674594/Archive.zip)

**Comment by mnblonsky** [comment]
This is a bigger issue than it seems. HPXML Doors (and windows) don't specify the interior/exterior zones in the same way as other boundaries. So even if the R values are consistent, we may be modeling garage doors as regular doors, which isn't good. Same potentially goes for basement doors, and windows to the garage or foundation.

I started fixing this last week, there's a fairly simple way to check which zones the windows/doors are connected to. We also need a garage door material in our lookup table. I'll create a PR for this soon.

**Comment by jmaguire1** [comment]
Thanks for looking into this @mnblonsky! FYI basements will never have doors, it's just the living space and garage. So we can take that off the list as a potential concern, but garage doors will come up quite a bit.

**Comment by mnblonsky** [comment]
I think we merged the PR before fully testing, but it does look like this is working now. Here's the properties output for that case (FYI, the Archive.zip doesn't have the in.xml file)

```
        "Door": {
            "Interior Zone": "Indoor",
            "Exterior Zone": "Outdoor",
            "Area (m^2)": [
                1.8580607999999998
            ],
            "Azimuth (deg)": [
                45
            ],
            "Boundary R Value": 7.14
        },
        "Garage Door": {
            "Interior Zone": "Garage",
            "Exterior Zone": "Outdoor",
            "Area (m^2)": [
                9.10449792
            ],
            "Azimuth (deg)": [
                45
            ],
            "Boundary R Value": 5.0
        },
```
