### ISSUE TITLE
HPXML updates to pools and spas

### ISSUE THREAD

**Issue by jmaguire1** [NREL/OCHRE#76]
There's a coming HPXML breaking change to the inputs for pools and spas that we'll have to handle: https://github.com/orgs/NREL/projects/78?pane=issue&itemId=39882114 .

This is going to break something in ResStock when it gets integrated, that's probably about a month out though. Just wanted to highlight this so when we start seeing hpxml files that break the workflow we know what we'll have to update.

**Comment by mnblonsky** [comment]
Fixed with #132
